version: 2.1
orbs:
    github: arrai/github@5.0.0
    lintinator: arrai/lintinator@2.1.2
    pypi: arrai/pypi@3.1.0
    pytest: arrai/pytest@10.0.1
executors:
    python:
        docker:
            - image: cimg/python:3.10
jobs:
    build:
        executor: python
        resource_class: small
        steps:
            - checkout
            - run:
                  name: Verify Git Tag Matches Python Version
                  command: |
                      GIT_TAG=$(git describe --tags --exact-match 2>/dev/null)

                      if [ $? -ne 0 ]; then
                        echo "No exact match Git tag found."
                        exit 1
                      fi

                      PYTHON_VERSION=$(python -c "import rets; print(rets.__version__)")

                      if [ "$GIT_TAG" == "v$PYTHON_VERSION" ]; then
                        echo "Git tag matches the Python version: $GIT_TAG"
                        exit 0
                      else
                        echo "Git tag ($GIT_TAG) does not match the Python version ($PYTHON_VERSION)."
                        exit 1
                      fi
            - run:
                  name: Build Package
                  command: uv build --wheel
            - save_cache:
                  paths:
                      - ~/project/dist
                  key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
workflows:
    lint:
        jobs:
            - lintinator/lint_python_fixed_ip:
                  name: lint
                  context: arrai-global
                  executor: lintinator/python310
                  hooks: ruff
                  filters:
                      branches:
                          only:
                              - main
            - lintinator/lint_python:
                  name: lint-no-badge
                  executor: lintinator/python310
                  hooks: ruff
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
    test:
        jobs:
            - pytest/pytest_fixed_ip:
                  name: python_3.10
                  executor: pytest/python310
                  resource_class: small
                  context: arrai-global
                  filters:
                      branches:
                          only:
                              - main
            - pytest/pytest_fixed_ip:
                  name: python_3.10-no-badge
                  executor: pytest/python310
                  resource_class: small
                  context: arrai-global
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - pytest/pytest_fixed_ip:
                  name: python_3.11
                  executor: pytest/python311
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  filters:
                      branches:
                          only:
                              - main
            - pytest/pytest:
                  name: python_3.11-no-badge
                  executor: pytest/python311
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - pytest/pytest_fixed_ip:
                  name: python_3.12
                  executor: pytest/python312
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  filters:
                      branches:
                          only:
                              - main
            - pytest/pytest:
                  name: python_3.12-no-badge
                  executor: pytest/python312
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - pytest/pytest_fixed_ip:
                  name: python_3.13
                  executor: pytest/python313
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  filters:
                      branches:
                          only:
                              - main
            - pytest/pytest:
                  name: python_3.13-no-badge
                  executor: pytest/python313
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - pytest/pytest_fixed_ip:
                  name: python_3.14
                  executor: pytest/python314
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  filters:
                      branches:
                          only:
                              - main
            - pytest/pytest:
                  name: python_3.14-no-badge
                  executor: pytest/python314
                  resource_class: small
                  context: arrai-global
                  build_coverage: false
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - build:
                  name: build
                  requires:
                      - python_3.10-no-badge
                      - python_3.11-no-badge
                      - python_3.12-no-badge
                      - python_3.13-no-badge
                      - python_3.14-no-badge
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - pypi/upload_release:
                  name: publish
                  cache_key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
                  context: arrai-private-package-publishing
                  requires:
                      - build
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - github/create_release:
                  name: release_on_github
                  context: arrai-global
                  requires:
                      - build
                  filters:
                      tags:
                          only: /^(?:[0-9]+[.]){2}[0-9]+$/
                      branches:
                          ignore: /.*/
            - github/create_release:
                  name: prerelease_on_github
                  context: arrai-global
                  prerelease: true
                  requires:
                      - build
                  filters:
                      tags:
                          only: /^(?:[0-9]+[.]){2}[0-9]+(?:[AaBb]|RC|rc)[0-9]*$/
                      branches:
                          ignore: /.*/

